"""empty message

Revision ID: 0bcc5f8e3934
Revises: 2c6e8b7038b5
Create Date: 2016-11-12 11:40:40.191295

"""

# revision identifiers, used by Alembic.
revision = '0bcc5f8e3934'
down_revision = '2c6e8b7038b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time_slot_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('stop_time', sa.DateTime(), nullable=True),
    sa.Column('facility_name', sa.String(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'time_slots', sa.Column('appointment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'time_slots', 'appointments', ['appointment_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_slots', type_='foreignkey')
    op.drop_column(u'time_slots', 'appointment_id')
    op.drop_table('appointments')
    ### end Alembic commands ###
