"""empty message

Revision ID: 15613f4d85d6
Revises: df2bb2533c41
Create Date: 2016-12-13 12:34:15.015011

"""

# revision identifiers, used by Alembic.
revision = '15613f4d85d6'
down_revision = 'df2bb2533c41'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'time_slots_user_id_fkey', 'time_slots', type_='foreignkey')
    op.create_foreign_key(None, 'time_slots', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_slots', type_='foreignkey')
    op.create_foreign_key(u'time_slots_user_id_fkey', 'time_slots', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###
