"""empty message

Revision ID: 1df711c2eea1
Revises: 668a1e76a72d
Create Date: 2016-11-23 12:25:49.926559

"""

# revision identifiers, used by Alembic.
revision = '1df711c2eea1'
down_revision = '668a1e76a72d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('end_time', sa.JSON(), nullable=True))
    op.add_column('appointments', sa.Column('start_time', sa.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'start_time')
    op.drop_column('appointments', 'end_time')
    ### end Alembic commands ###
