"""empty message

Revision ID: 1e1909be628e
Revises: 6e8c2c038780
Create Date: 2016-12-01 12:33:02.411728

"""

# revision identifiers, used by Alembic.
revision = '1e1909be628e'
down_revision = '6e8c2c038780'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('arrived', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'arrived')
    ### end Alembic commands ###
