"""empty message

Revision ID: 2026d8328515
Revises: 75359eac034e
Create Date: 2016-11-21 13:57:29.787552

"""

# revision identifiers, used by Alembic.
revision = '2026d8328515'
down_revision = '75359eac034e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.drop_column('appointments', 'stop_time')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('stop_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('appointments', 'end_time')
    ### end Alembic commands ###
