"""empty message

Revision ID: 2c6e8b7038b5
Revises: 766a4942bcd0
Create Date: 2016-11-12 11:40:01.372012

"""

# revision identifiers, used by Alembic.
revision = '2c6e8b7038b5'
down_revision = '766a4942bcd0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_slots',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('start_hour', sa.Float(), nullable=True),
    sa.Column('end_hour', sa.Float(), nullable=True),
    sa.Column('start_str', sa.String(), nullable=True),
    sa.Column('end_str', sa.String(), nullable=True),
    sa.Column('booked', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_slots')
    ### end Alembic commands ###
