"""empty message

Revision ID: 668a1e76a72d
Revises: 2026d8328515
Create Date: 2016-11-23 12:20:22.432908

"""

# revision identifiers, used by Alembic.
revision = '668a1e76a72d'
down_revision = '2026d8328515'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'start_time')
    op.drop_column('appointments', 'end_time')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
