"""empty message

Revision ID: 66f5e9b2b697
Revises: 721fbdb22445
Create Date: 2016-11-23 12:35:55.221628

"""

# revision identifiers, used by Alembic.
revision = '66f5e9b2b697'
down_revision = '721fbdb22445'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('appointments', sa.Column('start_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'start_time')
    op.drop_column('appointments', 'end_time')
    ### end Alembic commands ###
