"""empty message

Revision ID: 6e8c2c038780
Revises: 66f5e9b2b697
Create Date: 2016-11-28 22:50:01.788685

"""

# revision identifiers, used by Alembic.
revision = '6e8c2c038780'
down_revision = '66f5e9b2b697'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('station_id', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('station_number', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'stations', ['station_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'station_number')
    op.drop_column('appointments', 'station_id')
    ### end Alembic commands ###
