"""empty message

Revision ID: 721fbdb22445
Revises: 1df711c2eea1
Create Date: 2016-11-23 12:35:06.063542

"""

# revision identifiers, used by Alembic.
revision = '721fbdb22445'
down_revision = '1df711c2eea1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'start_time')
    op.drop_column('appointments', 'end_time')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('end_time', postgresql.JSON(astext_type=Text()), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('start_time', postgresql.JSON(astext_type=Text()), autoincrement=False, nullable=True))
    ### end Alembic commands ###
