"""empty message

Revision ID: 7227340061e7
Revises: 4a3dbab7805c
Create Date: 2017-01-08 19:34:21.074708

"""

# revision identifiers, used by Alembic.
revision = '7227340061e7'
down_revision = '4a3dbab7805c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('recurring', sa.Boolean(), nullable=True))
    op.drop_column('time_slots', 'recurring')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_slots', sa.Column('recurring', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('appointments', 'recurring')
    ### end Alembic commands ###
