"""empty message

Revision ID: 75359eac034e
Revises: 0bcc5f8e3934
Create Date: 2016-11-15 11:23:51.426081

"""

# revision identifiers, used by Alembic.
revision = '75359eac034e'
down_revision = '0bcc5f8e3934'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_slots', sa.Column('day', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_slots', 'day')
    ### end Alembic commands ###
