"""empty message

Revision ID: df2bb2533c41
Revises: 1e1909be628e
Create Date: 2016-12-01 13:04:32.826327

"""

# revision identifiers, used by Alembic.
revision = 'df2bb2533c41'
down_revision = '1e1909be628e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('arrived_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'arrived_at')
    ### end Alembic commands ###
