"""empty message

Revision ID: fd652cb887e8
Revises: 15613f4d85d6
Create Date: 2016-12-15 10:21:27.500706

"""

# revision identifiers, used by Alembic.
revision = 'fd652cb887e8'
down_revision = '15613f4d85d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('reminded', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'reminded')
    ### end Alembic commands ###
